### ISSUE TITLE
Error while starting training

### ISSUE THREAD

**Issue by madr3z** [MarioDuran/TYolov5#3]
I have set up the dataset etc. When I start training in one of the models' directory (eg. "/1 SConvLSTM/yolov5/", I get the following error after the image scanning is done:

`Scanning labels ../../../../datasets//all_in_one/train/labels.cache (20942 found, 0 missing, 3847 empty, 0 duplicate, for 24789 images): 24789it [00:00, 30033.60it/s]
Traceback (most recent call last):
  File "train.py", line 544, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 196, in train
    testloader = create_dataloader(test_path, imgsz_test, total_batch_size, gs, opt,
  File "/home/local/xxxx/TYolov5/1 SConvLSTM/yolov5/utils/datasets.py", line 54, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/home/local/xxxx/TYolov5/1 SConvLSTM/yolov5/utils/datasets.py", line 385, in __init__
    cache = torch.load(cache_path)  # load
  File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: STACK_GLOBAL requires str`

I looked around and it seems that the issue might be caused by loading the cached labels. What do you think would fix the issue?

**Comment by madr3z** [comment]
I found the problem: it was due to a previously made cache file by an updated yolov5 from Ultralytics repo.
