### ISSUE TITLE
Could not broadcast input array from shape (3,576,640) into shape (3,576,576)

### ISSUE THREAD

**Issue by madr3z** [MarioDuran/TYolov5#4]
When I start training, at the end of the first epoch (not finished), the following error appears:

`Traceback (most recent call last):
  File "train.py", line 547, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 300, in train
    for i, (imgs, targets, paths, _, masks, masksOP) in pbar:  # batch -------------------------------------------------------------
  File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/local/xxxx/proj/baseline_testing/TYolov5/1 SConvLSTM/yolov5/utils/datasets.py", line 794, in __getitem__
    images[i, :, :, :] = img
ValueError: could not broadcast input array from shape (3,576,640) into shape (3,576,576)`

Do you know what might have caused the problem? I tried both rectangular training and normal size training and non of them seemed to affect this issue.

**Comment by MarioDuran** [comment]
Let me give it a check, gonna give you an update soon.

**Comment by heartworm1** [comment]
> When I start training, at the end of the first epoch (not finished), the following error appears:
> 
> `Traceback (most recent call last): File "train.py", line 547, in <module> train(hyp, opt, device, tb_writer) File "train.py", line 300, in train for i, (imgs, targets, paths, _, masks, masksOP) in pbar: # batch ------------------------------------------------------------- File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__ for obj in iterable: File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__ data = self._next_data() File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data return self._process_data(data) File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data data.reraise() File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise raise self.exc_type(msg) ValueError: Caught ValueError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop data = fetcher.fetch(index) File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp> data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/local/xxxx/proj/baseline_testing/TYolov5/1 SConvLSTM/yolov5/utils/datasets.py", line 794, in __getitem__ images[i, :, :, :] = img ValueError: could not broadcast input array from shape (3,576,640) into shape (3,576,576)`
> 
> Do you know what might have caused the problem? I tried both rectangular training and normal size training and non of them seemed to affect this issue.

so did you solve it?

**Comment by cccc18** [comment]
> > 当我开始训练时，在第一个纪元（未完成）结束时，出现以下错误：
> > `Traceback (most recent call last): File "train.py", line 547, in <module> train(hyp, opt, device, tb_writer) File "train.py", line 300, in train for i, (imgs, targets, paths, _, masks, masksOP) in pbar: # batch ------------------------------------------------------------- File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__ for obj in iterable: File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__ data = self._next_data() File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data return self._process_data(data) File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data data.reraise() File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise raise self.exc_type(msg) ValueError: Caught ValueError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop data = fetcher.fetch(index) File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/local/xxxx/miniconda3/envs/tyolo/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp> data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/local/xxxx/proj/baseline_testing/TYolov5/1 SConvLSTM/yolov5/utils/datasets.py", line 794, in __getitem__ images[i, :, :, :] = img ValueError: could not broadcast input array from shape (3,576,640) into shape (3,576,576)`
> > 您知道是什么原因导致了这个问题吗？我尝试了矩形训练和正常尺寸训练，但似乎都没有影响这个问题。
> 
> 那么你解决了吗？

Hello. I'm sorry to bother you. Have you solved this problem? I also had this problem.
