### ISSUE TITLE
There was a problem reproducing SQRNN

### ISSUE THREAD

**Issue by MrReeed** [MarioDuran/TYolov5#5]
I am honored to read your article and code. An unexpected situation occurred when I reproduced SQRNN: `IndexError: list index out of range` occurred at `line 789` of `datasets.py` at `img = self.imgs[index]`. I checked the code logic and found that the index of `self.seq[indices[0], i]` from `current_indices= [self.seq[indices[0], i], self.seq[indices[1], i],
                                                                         self.seq[indices[2], i], self.seq[indices[3], i]]` at `line 571` is wrong. I have a total of 758 training images (index values from 0 to 757), but the code index is 758. Out of range. And this `self.seq` comes from the `def create_sequences` function, you may understand the logical relationship here better. I don’t know how to solve this problem, I hope you can help me, thank you very much😄

**Comment by MrReeed** [comment]
I saw in the previous Issues, you said that you will update the code,  looking forward to your update

**Comment by MrReeed** [comment]
Oh, the complete error is as follows:

 Traceback (most recent call last):
  File "D:\WisdomFire\YOLOv5\TYOLOv5\TYolov5\4 SQRNN\yolov5\train.py", line 551, in <module>
    train(hyp, opt, device, tb_writer)
  File "D:\WisdomFire\YOLOv5\TYOLOv5\TYolov5\4 SQRNN\yolov5\train.py", line 299, in train
    for i, (imgs, targets, paths, _, masks, masksOP) in pbar:  # batch -------------------------------------------------------------
  File "D:\Anaconda\envs\yolov5_5_pytorch\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "D:\Anaconda\envs\yolov5_5_pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\yolov5_5_pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda\envs\yolov5_5_pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\yolov5_5_pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\WisdomFire\YOLOv5\TYOLOv5\TYolov5\4 SQRNN\yolov5\utils\datasets.py", line 576, in __getitem__
    img, mask, labels = load_mosaic(self, current_indices, yc, xc, i, r)
  File "D:\WisdomFire\YOLOv5\TYOLOv5\TYolov5\4 SQRNN\yolov5\utils\datasets.py", line 877, in load_mosaic
    img, mask, _, (h, w) = load_image(self, index)
  File "D:\WisdomFire\YOLOv5\TYOLOv5\TYolov5\4 SQRNN\yolov5\utils\datasets.py", line 789, in load_image
    img = self.imgs[index]
IndexError: list index out of range

Process finished with exit code 1

**Comment by MiladGhorbaniG** [comment]
I got the same issue

**Comment by wch243294382** [comment]
have you solved this problem？

**Comment by MrReeed** [comment]
你好！邮件我已收到，谢谢~

**Comment by MiladGhorbaniG** [comment]
I resolved it by editing datasets.py. The issue is with the last index. For example you can ignore last sequence in datasets.py to avoid error.

**Comment by wch243294382** [comment]
> I resolved it by editing datasets.py. The issue is with the last index. For example you can ignore last sequence in datasets.py to avoid error.

can you show me your code，i cant solve this problem

**Comment by MiladGhorbaniG** [comment]
> > I resolved it by editing datasets.py. The issue is with the last index. For example you can ignore last sequence in datasets.py to avoid error.
> 
> can you show me your code，i cant solve this problem

I resolved it as follows: 
In 4 places of the `datasets.py` limited the index by adding the following code:

`
if index >= len(self.imgs): index = len(self.imgs)-1
`

the places are : 
1: line 294 in def update(self, index, cap)
2: line 547 In def __getitem__(self, index)
3: line 788 in def load_image(self, index)
4: line 866 in def load_mosaic(self, indices, yc, xc, num, r)

**Comment by cccc18** [comment]
> > > 我通过编辑 datasets.py 解决了它。问题出在最后一个索引上。例如，您可以忽略 datasets.py 中的最后一个序列以避免错误。
> > 
> > 
> > 你能给我看看你的代码吗，我无法解决这个问题
> 
> 我解决如下：在限制索引的 4 个地方，通过添加以下代码：`datasets.py`
> 
> `if index >= len(self.imgs): index = len(self.imgs)-1`
> 
> 这些地方是： 1：def update（self， index， cap） 中的第 294 行 2：def **getitem**（self， index） 中的第 547 行 3：def load_image（self， index） 中的第 788 行 4：def 中的第 866 行 load_mosaic（self， indices， yc， xc， num， r）

Hello. I'm sorry to bother you. I don't know if you can run the entire code successfully. I'm getting frequent errors when running this code, and I'm wondering if you can help me fix it. If possible, I hope you can leave your email or contact me doqi_huang@163.com

**Comment by MrReeed** [comment]
你好！邮件我已收到，谢谢~

**Comment by cccc18** [comment]
Hello. I'm sorry to bother you. I don't know if you can run the entire code successfully. I'm getting frequent errors when running this code, and I'm wondering if you can help me fix it. If possible, I hope you can leave your email or contact me doqi_huang@163.com

**Comment by cccc18** [comment]
> > > I resolved it by editing datasets.py. The issue is with the last index. For example you can ignore last sequence in datasets.py to avoid error.
> > 
> > 
> > can you show me your code，i cant solve this problem
> 
> I resolved it as follows: In 4 places of the `datasets.py` limited the index by adding the following code:
> 
> `if index >= len(self.imgs): index = len(self.imgs)-1`
> 
> the places are : 1: line 294 in def update(self, index, cap) 2: line 547 In def **getitem**(self, index) 3: line 788 in def load_image(self, index) 4: line 866 in def load_mosaic(self, indices, yc, xc, num, r)

If you can't contact me by that email, you can contact me by this email.   huangzhichao@dlmu.edu.cn  .thanks
